import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { addNewProduct, fetchAllProducts, fetchBrands, fetchCategories, fetchProductById, fetchProductsByFilters, fetchProductsBySort, updateProduct } from './productApi';

const initialState = {
  products: [],
  allProducts: [],
  status: 'idle',
  totalItems: 0,
  selectedProduct: null
};


export const fetchAllProductsAsync = createAsyncThunk(
  'product/fetchAllProducts',
  async (amount) => {
    const response = await fetchAllProducts();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);
export const fetchProductsByFiltersAsync = createAsyncThunk(
  'product/fetchProductsByFilters',
  async ({ filter, sort, pagination }) => {
    const data = await fetchProductsByFilters(filter, sort, pagination);

    return data;
  }
);
export const fetchProductByIdAsync = createAsyncThunk(
  'product/fetchProductById',
  async (id) => {
    const data = await fetchProductById(id);

    return data;
  }
);

export const fetchCategoriesAsync = createAsyncThunk(
  'product/fetchCategories',
  async () => {
    const response = await fetchCategories();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fetchBrandsAsync = createAsyncThunk(
  'product/fetchBrands',
  async () => {
    const response = await fetchBrands();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const addNewProductAsync = createAsyncThunk(
  'product/addNewProduct',
  async (product) => {
    const res =await addNewProduct(product)
    return res
  }
)

export const upadteProductAsync = createAsyncThunk(
  `product/updateProduct`,
  async(product) => {

    console.log('product update before',product)
    const res =await updateProduct(product)
    console.log('product update',product,res)
    return res
  }

)


export const productSlice = createSlice({
  name: 'product',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    resetProductForm: (state) => {

      state.selectedProduct = null;
    },

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchAllProductsAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchAllProductsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.allProducts = action.payload;
      })
      .addCase(fetchProductsByFiltersAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchProductsByFiltersAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.products = action.payload.products;
        state.totalItems = action.payload.totalItems;
      })
      .addCase(fetchCategoriesAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchCategoriesAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.categories = action.payload;
      })
      .addCase(fetchBrandsAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchBrandsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.brands = action.payload;
      })
      .addCase(fetchProductByIdAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchProductByIdAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.selectedProduct = action.payload;
      })
      .addCase(addNewProductAsync.pending, (state, action) => {
        state.status = 'loading'
      })
      .addCase(addNewProductAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.allProducts.push(action.payload)
      })
      .addCase(upadteProductAsync.pending, (state, action) => {
        state.status = 'loading'
      })
      .addCase(upadteProductAsync.fulfilled, (state, action) => {
        console.log('action',action,action.payload)
        state.status = 'idle';
        let index = state.allProducts.findIndex(product => product.id === action.payload.id)
        state.allProducts[index] = action.payload
      })

  },
});

export const { resetProductForm } = productSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectAllProducts = state => state.product.products;
export const selectCategories = state => state.product.categories;
export const selectBrands = state => state.product.brands;
export const selectedProductById = state => state.product.selectedProduct;
export const selectTotalItems = state => state.product.totalItems;


export default productSlice.reducer;
