import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { createUser, fetchUser, updateUserAddress } from './authApi';

const initialState = {
  user: null,
  loggedInUser:null,
  error:null,
  status: 'idle',
};


export const createUserAsync = createAsyncThunk(
  'users/createUsers',
  async (userData) => {
    const response = await createUser(userData);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);
export const fetchUserAsync = createAsyncThunk(
  'user/fetchUser',
  async (loginData) => {
    const response = await fetchUser(loginData);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);
export const updateUserAddressAsync = createAsyncThunk(
  'user/updateUserAddress',
  async (update) => {
    const response = await updateUserAddress(update);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const authSlice = createSlice({
  name: 'users',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {

      state.value += 1;
    },
   
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
    .addCase(createUserAsync.pending, (state) => {
      state.status = 'loading';
    })
    .addCase(createUserAsync.fulfilled, (state, action) => {
      state.status = 'idle';
        state.user = action.payload;
      })
      .addCase(fetchUserAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchUserAsync.fulfilled, (state, action) => {
      console.log("data",state,action)
        state.status = 'idle';
        state.loggedInUser = action.payload[0];
      })
      .addCase(fetchUserAsync.rejected, (state, action) => {
        state.status = 'idle';
        state.error = action.error;
      })
      .addCase(updateUserAddressAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(updateUserAddressAsync.fulfilled, (state, action) => {
        console.log('update address',action)
        state.status = 'idle';
          state.loggedInUser = action.payload;
        })
  },
});

export const { increment } = authSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectCount = (state) => state.counter.value;
export const selectUser = (state) => state.auth.user;


export default authSlice.reducer;
